version: "3.4"

services:
  front:
    build: .
    restart: unless-stopped
    expose:
        - 3000
    volumes:
        - .:/app
    container_name: auto-screening
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auto_screening.rule=Host(`auto-screening.colcolt.eu`)"
      - "traefik.http.routers.auto_screening.entrypoints=websecure"
      - "traefik.http.routers.auto_screening.tls.certresolver=myresolver"
      - "traefik.http.routers.auto_screening.tls=true"
      - "traefik.http.services.auto_screening.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik"
    networks:
      - traefik

networks:
  traefik:
    external: true
